### ISSUE TITLE
missing factory function?

### ISSUE THREAD

**Issue by stevemao** [hemanth/functional-programming-jargon#101]
factory is a function for creating other objects (functions).

**Comment by jethrolarson** [comment]
I don't really see factory as a functional term. Anyone else disagree?

**Comment by klioen** [comment]
it's a design pattern in oop

**Comment by jethrolarson** [comment]
Yeah. I get that. Partial application is essentially the equivalent thing,
I think.

**Comment by hemanth** [comment]
> Partial application is essentially the equivalent thing 

^
