### ISSUE TITLE
Writing style

### ISSUE THREAD

**Issue by idf** [hemanth/functional-programming-jargon#108]
In Higher-Order Function, 
```js
const filter = (pred, xs) => ...
```

For this one, is it better to explicitly use `predicate` rather than `pred`? Because the former one is more explicit, and for documentation we tend to favor explicit.

**Comment by MichalZalecki** [comment]
I think it's like arr and array. It's so obvious that people just get that
without much thinking.

28.08.2016 00:15 "Daniel D. Zhang" <notifications@github.com> napisał(a):

**Comment by jethrolarson** [comment]
I'm okay with using the full word if it helps people. Non fp people often
don't know what a predicate is anyway.

**Comment by idf** [comment]
It really depends on the targeting audience of the this document. Unless it were for advanced readers, `pred` and other short forms would not benefit much.

**Comment by jethrolarson** [comment]
It's not for advanced people. It's for beginners
