### ISSUE TITLE
Use of blockquote

### ISSUE THREAD

**Issue by raine** [hemanth/functional-programming-jargon#11]
The current use of blockquote makes it look as if paragraphs are quoting some other sources.

**Comment by hemanth** [comment]
Hmm, true. `__ __` would be good?

**Comment by jethrolarson** [comment]
What's the intent with the blockquote? Is is just to distinguish the summary from the example text?

**Comment by hemanth** [comment]
@jethrolarson The idea was to keep the summary as small as possible and blockquote looked neat then.

**Comment by jethrolarson** [comment]
Close?
