### ISSUE TITLE
use js standard style

### ISSUE THREAD

**Issue by jethrolarson** [hemanth/functional-programming-jargon#111]
While I recognize that this is no official standard I find it a useful preset. 

https://github.com/feross/standard

We can mix this with something like 
https://github.com/eslint/eslint-plugin-markdown
To enforce that code examples follow our standards.

**Comment by Alhadis** [comment]
Thanks for making it harder to read.

**Comment by jethrolarson** [comment]
Anytime

**Comment by sotojuan** [comment]
As much as I love Standard the no semis is a big polarizing problem so it'd be better if we stick to xo or a regular esling config.

**Comment by jethrolarson** [comment]
You're probably right. I don't really mind losing the people that would
drop sarcastic comments on an open source issue though

**Comment by Alhadis** [comment]
Alright, here's an earnest one:

2-SPACE TABSTOPS ARE HARD TO READ.

**Comment by jethrolarson** [comment]
Thanks. That's more informative. I was assuming you didn't like omitting
semicolons

**Comment by Alhadis** [comment]
I don't like that either, but I can stand it more than cramped code.

**Comment by sotojuan** [comment]
I think since the code in this repo is generally small and only for examples, 4 spaces is fine.

**Comment by jethrolarson** [comment]
Yeah, that's true.

I'd hoped that the "standard" preset would prevent bikeshedding. Guess I
chose wrong

**Comment by jethrolarson** [comment]
I don't know why I left this issue open. Code was merged. If there are outstanding objections they can be new issues

**Comment by Alhadis** [comment]
@jethrolarson I believe what the "Standard" style means about "preventing bikeshedding" is to stop dev teams from disagreeing over stylistic differences. Forcing it on other people's codebases comes across as pushy and evangelical, and accomplishes absolutely nothing in the long term.

Having said that, I don't see any commits where one contributor has modified the formatting of another's contribution (aside from yours).

**Comment by jethrolarson** [comment]
I don't have merge perms so if hemanth wasn't willing to take the update he
could have declined the PR. I'm not forcing anyone.  This was a proposal,
it was accepted. Having some standard is good for consistency, my pr here
identified some actual errors too (thanks to eslint). I picked a standard,
you disagree. That's fine, but I think your objections are preferential so
I'm not inclined to change it.

If you have research stating that 4 spaces has been shown to be more easy
to read then that'd be really cool and I think that would warrant
submitting PRs to feross/standard and a bunch of others.

I'm just a fan of this project and want it to help people

**Comment by Alhadis** [comment]
So, what stopped you fixing the errors without stylistic alterations?

> Having some standard is good for consistency

What was inconsistent about the existing formatting? It was fine.

**Comment by jethrolarson** [comment]
I was proposing a standard style for consistency so that there aren't stylistic differences between examples. There were already stylistic differences creeping in: semi-colon usage, parens around arguments, whitespace, etc. I wasn't even consistent with myself in my edits as I use different standards for work vs personal. I've gotten a lot of value out of eslint at work as it prevents style issues from coming up in PR (which are incrementally low value arguments to have), and it has prevented a slew of actual errors as well. I considered setting up a lint file for this repo that would roughly match what we seemed to already be doing, but I thought my choices on style there would be argued as being just my preferences. I remembered the "js standard style" preset and thought choosing a decently well used preset was preferable to getting into long winded arguments on spaces vs tabs. The setup was moderately easy and and could be validated as a build process. 

Git push ; create pull-request
I see merge

**Comment by jethrolarson** [comment]
What is the outcome you're seeking?

**Comment by Alhadis** [comment]
I'd argue that stylistic variation is a more organic and realistic approach to explaining functional programming to readers who're probably from all sorts of backgrounds, not just JavaScript.

In any case, if I'd done what you did, I would've deliberately altered the preset to retain as much of the original formatting as possible, while ironing out the discrepancies. E.g., if most of the lines ended in semicolons, then the ones which didn't had semicolons added. The reverse logic is true.
