### ISSUE TITLE
Union type code example misleading

### ISSUE THREAD

**Issue by stereobooster** [hemanth/functional-programming-jargon#117]
Hi. First of all thanks for starting this repo.

`Union type` code is a bit misleading from my POV. It is rather shows concepts of `polymorphic function` and `coercion`. Polymorphic functions are functions whose parameters can have more than one type.
### Polymorphic function in **dynamic language** (JavaScript, Ruby, etc)

``` javascript
function draw(shape) { ... }
```

There is no type check so you do not need to do anything special. **Pros**: polymorphic functions for free. **Cons**: runtime errors e.g. `undefined is not a function` etc.
### Polymorphic function in **static language without ADT** (Go; C++, Java etc)

``` Go
type Shape interface { ... }
type Circle struct { ... }
type Square struct { ... }

func draw(a Shape) { 
  // type of value common interface  e.g. Shape, not exact type (Circle or Square)
}
```

There is slight difference between structural and nominal type systems.
### Polymorphic function in **static language with ADT** ([TypeScript](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/) etc)

``` TypeScript
interface Circle {
    kind: "circle";
    radius: number;
}

interface Square {
    kind: "square";
    sideLength: number;
}

type Shape = Circle | Square;

function draw(shape: Shape) {
    switch (shape.kind) {
        case "circle": ... //type of value Circle, not Shape
        case "square": ... //type of value Square, not Shape
    }
}
```

The main power of `disjoint union` shines in static type system with support of `match` statement (so compiler tracks if you handling all cases).

**Comment by jethrolarson** [comment]
Thanks for the thoughtful feedback. 

However, I'm not sure how to change the description to make it more accurate. As you know, JavaScript is I'll suited for describing the concept. There's a couple libraries that try to capture the value of ADTs(daggy, union-type) but they're not staticly checked, so it's not the same.

Are you proposing that we discard the term and choose to describe polymorphism instead

**Comment by stereobooster** [comment]
I'm proposing to describe it in statical type system (TypeScript or Flow) and as of JS it doesn't make much sense (you do not need it, you can mix anything you want). And add section for ADT (algebraic) saying that union and product is part of ADT.

I saw request for describing polymorphism in other ticket, so probably good idea to add it too. For polymorphism there are following classifications:

```
----------------[Strachey, 1967]-----------------

                  +-- parametric
  polymorphism ---+
                  +-- ad-hoc

----------------[Cardelli, 1985]-----------------
                                  +-- parametric
                  +-- universal --+              
                  |               +-- inclusion 
  polymorphism ---+                       
                  |               +-- overloading
                  +-- ad-hoc -----+
                                  +-- coercion
```

This is a bit offtopic, sorry for that. But if we started talking about that...

**Comment by stereobooster** [comment]
I see it this way:

There are dynamically typed functional programming (LISP, Scheme) and statically typed functional programing (Haskell, OCaml).

Some concept of statically typed FP make sense in dynamically type system too, like functors, monads. But some does not make any sense without types, like disjoint union. It is like explain why you need umbrella to the fish. It does not solve real problem in this system. So for those things we need to go with typed JS e.g. TypeScript or Flow. Of course it make sense to explain as much as possible in pure ES6.

Additionally think of section of explaining common terms which can be applied to FP and/or OOP, like polymorphism, type systems, common data structures. Related articles:
 - https://eev.ee/blog/2016/07/26/the-hardest-problem-in-computer-science/
 - http://www.itu.dk/courses/BPRD/E2013/fundamental-1967.pdf
 - https://gist.github.com/garybernhardt/122909856b570c5c457a6cd674795a9c

What do you think?

**Comment by jethrolarson** [comment]
In the existing definition I tried to explain a union-type as a conceptual model that isn't enforced by a compiler. I still think that has some value in explaining the concept. We could go deeper with typescript. 

I think including a little typescript in this document  could be okay as long as it's only used for the concepts that require it.

**Comment by stereobooster** [comment]
There are more than one POV to approach this problem. I see at least two right away: 

**1.** Describe types as sets and you immediately get: union type - union of sets, record or product type - cartesian product, subtyping - subsets. But this approach is more logician way to see problem. It is Bertrand Russell invented type theory as a work around to paradoxes in set theory, though current type theory is a bit other thing than what Russell invented. 

**2.** More computer science way to see things: union type is one of the ways to achieve polymorphism in static type system. In dynamic type system, JS for example, you do not have problems with polymorphism, because you do not do static type checking. Everything polymorphic right away - one size fits all.

If you still want to get equivalence of union types in JS you need to add type checking to already existing polymorphism. Examples (taken [here](https://www.typescriptlang.org/docs/handbook/advanced-types.html)):

TS:
```TypeScript
/**
 * Takes a string and adds "padding" to the left.
 * If 'padding' is a string, then 'padding' is appended to the left side.
 * If 'padding' is a number, then that number of spaces is added to the left side.
 */
function padLeft(value: string, padding: string | number) {
    // ...
}
```

JS:
```JavaScript
function padLeft(value, padding) {
    if(!isString(padding) && !isNumber(padding)) throw new Error('TypeError: padding should be string or number');
}
```

TS:
```TypeScript
type Easing = "ease-in" | "ease-out" | "ease-in-out";
class UIElement {
    animate(dx: number, dy: number, easing: Easing) {
        if (easing === "ease-in") {
            // ...
        }
        else if (easing === "ease-out") {
        }
        else if (easing === "ease-in-out") {
        }
        else {
            // error! should not pass null or undefined.
        }
    }
}
```

JS:
```JavaScript
let easings = ["ease-in", "ease-out", "ease-in-out"]
class UIElement {
    animate(dx, dy, easing) {
        if (easings.indexOf(easing) == -1)  throw new Error('TypeError: unknown type of easing: ' + easing);
    }
}
```

Note: static type checker will also proved exhaustive check for Union types, which will reduce human errors.

Makes sense?

**Comment by jethrolarson** [comment]
Yeah that makes sense. Both approaches kind of work. Could also use tagged
union ad an alternative

**Comment by stereobooster** [comment]
And even more thoughts on Subject. JS corresponds to untyped lambda (am I correct on this?). At this point it is worth to mention [lambda-cube](http://www.uio.no/studier/emner/matnat/ifi/INF5160/h13/timeplan/bock_dependent_types.pdf).
