### ISSUE TITLE
Add real world examples and alternative names

### ISSUE THREAD

**Issue by stereobooster** [hemanth/functional-programming-jargon#119]
Add examples from real world examples.

For example section on monads. Alternative name for `chain` is `flatMap` (or `flat_map` or `flatmap`). Real world example is streams for instance [in highland](http://highlandjs.org/#flatMap). 

For example section on functors. Real world example: of course `Array`. But also [`Streams`](https://streams.spec.whatwg.org/) and [`Promises`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise). In `Promises` `map` is called `then`.

I believe this can be helpful.

**Comment by jethrolarson** [comment]
I didn't want to have to explain a bunch of types that aren't built into JavaScript. 

Promise.then is actually both the map and flatmap interface which I think makes using it for the explanation confusing

**Comment by jethrolarson** [comment]
There is a section on Maybe which has chain/flatmap used. Maybe it's worth linking from the monad section

**Comment by stereobooster** [comment]
> Promise.then is actually both the map and flatmap interface which I think makes using it for the explanation confusing

I didn't know that. Worth to mention that fact.

When `onFulfilled` returns promise (generally "thenable" object) then `then` works as `flatMap`, If returned value is not promise  then it works as `map`.

Links: https://promisesaplus.com/, https://gist.github.com/briancavalier/3296186

**Comment by jethrolarson** [comment]
We've added the name aliases for chain. I'm not comfortable saying that `then` is equivalent to `map`. I think we should add a section on Future/Promise/Task to explain the functor aspects of those types.
