### ISSUE TITLE
Partial application as currying

### ISSUE THREAD

**Issue by stereobooster** [hemanth/functional-programming-jargon#124]
The simplest example for currying:

```
(A,B) -> C convert to (A) -> (B -> C)
```

So partial application is application to curried function

```
((A,B) -> C)(A)  convert to ((A) -> (B -> C))(A)
```

From this definition I can not see difference between Auto-currying and partial application. Am I wrong?

**Comment by jethrolarson** [comment]
You're not wrong,  auto-currying is essentially dynamic partial
application. The only reason to describe it as "curry" is due to libraries
like Ramda and Lodash using it for the practice

**Comment by CrossEye** [comment]
I think there is a difference.

When you partially apply `k` arguments to a function with `n` formal parameters, you get back a new function that still needs `n - k` arguments.  (Assuming `k < n`, of course.)

When you auto-curry a function, you get a function that has useful behavior when supplied `1`, `2`, ..., or `n`  arguments.  If you supply `k` arguments, you get back an already auto-curried function with `n - k` formal parameters.

```js
const f = (a, b, c, d, e) => a + b + c + d + e;

partial(f, 1, 2)  ≍  (c, d, e) => 1 + 2 + c + 2 + e;

// But if

const g = autocurry(f)(1, 2);

// then

g ≍ (c, d, e) => 1 + 2 + c + d + e
g ≍  c => (d, e) =>  1 + 2 + c + d + e
g ≍  (c, d) => e =>  1 + 2 + c + d + e
g ≍  c => d => e =>  1 + 2 + c + d + e
```

So you can call this "dynamic partial application", but it's not partial application as it's usually used.

**Comment by stereobooster** [comment]
Maybe add a bit of history nerdiness?

> This replacement mechanism simplifies work in both combinatory logic and lambda calculus and would later be called currying, after Haskell Curry. While Curry attributed the concept to Schönfinkel, it had already been used by Frege.

**Comment by jethrolarson** [comment]
I think this is addressed in the current definitions. Reopen if you disagree.
