### ISSUE TITLE
Option elaboration

### ISSUE THREAD

**Issue by stereobooster** [hemanth/functional-programming-jargon#125]
If we explain `Option` as union type it would make sense to state that:

 - `Some` higher order type e.g. type that can wrap other type
 - `None` is unit type whose only value is `None`

```
Option = Some<Type> | None
```

But given JS code has nothing to do with types, it is rather explains `Option` as monad ([Maybe](https://wiki.haskell.org/Maybe) monad in Haskell classification).

**Comment by jethrolarson** [comment]
I don't like focusing on the Monad interface when describing types. You
don't say The Array Monad, The Promise Traversable, the Task Applicative.
Emphasizing monad just makes the concepts seem scarier.

Sorry for the rant

**Comment by stereobooster** [comment]
I'm not a fan of monads myself, but the code example is about monads and not types (that is my point).
Offtopic. Just in case it wasn't clear or something wrong with my wording: I'm not criticising this work, just trying to make it better.

**Comment by jethrolarson** [comment]
No, I get you. I was just having an argument with myself. I think I put
option in the document to give a more useful example of chain/bind since
array doesn't really illuminate what it's good for
