### ISSUE TITLE
Add Combinator Definition

### ISSUE THREAD

**Issue by amilajack** [hemanth/functional-programming-jargon#126]

**Comment by jethrolarson** [comment]
You know what you'd like it to say?

**Comment by hemanth** [comment]
Are you referring to Fixed-point combinator?

**Comment by jethrolarson** [comment]
There's a whole bunch of them. S, K, B, C, I, W, and everything in aviary...

**Comment by hemanth** [comment]
And then there is Y 🤗

**Comment by stereobooster** [comment]
Most known fixed-point combinator is Y combinator, but it will not work in JS, because of order of evaluation. So there is Z combinator to the rescue

```js
// The Y combinator is defined as:
// Y          = λf.(λx.f (x x))(λx.f (x x))
// The Z combinator is defined as:
// Z          = λf.(λx.f (λv.((x x) v))) (λx.f (λv.((x x) v)))

const Z       = f => (x => f (v => ((x (x)) (v)))) (x => f (v => ((x (x)) (v))))
const factgen = fact => n => n < 2 ? 1 : n * fact(n-1)
const fact    = Z(factgen)
```

**Comment by stereobooster** [comment]
Other idea: we can expand `Lambda Calculus` section.

A lot of simple `Lambda Calculus` ideas pretty trivial to demonstrate in JS

```js
//True   = λt.λf.t
//False  = λt.λf.f
//Not    = λb.b False True

const True   = t => f => t
const False  = t => f => f
const Not    = b => b (False) (True)

const toBool = (churchBoolean) => churchBoolean (true) (false)

//Zero   = λf.λx.x
//Succ   = λn.λf.λx.f (n f x)

const Zero   = f => z => z
const Succ   = n => f => z => f (n (f) (z))
const toNumber = (churchNumeral) => churchNumeral((x) => x+1) (0)
```

But I suppose it can be separate page dedicated to Lambda Calculus.

**Comment by jethrolarson** [comment]
Church encoding is cool but I think it's too far away from being practical
to try to teach it here

**Comment by SeanSilke** [comment]
It would be nice to see definition of various combinations. The C combinator is rather practical and can be used in everyday coding.

**Comment by jethrolarson** [comment]
Would the combinator's all be curried?

**Comment by SeanSilke** [comment]
Don't sure that i get your question right. Yes C combinator is type of curing.
 My knowledge of combinators is rather limited, actually i get it from this great talk of Reginald Braithwaite https://youtu.be/3t75HPU2c44

**Comment by jethrolarson** [comment]
I think if we have combinators in the doc we should just have a general definition and now try to teach the details of every combinator. We can link out for that.

**Comment by stereobooster** [comment]
Also worth to elaborate a bit more, about why Y combinator does not work. It is because order of evaluation and add link to `Lazy evaluation` section

**Comment by jethrolarson** [comment]
Here's a whack at it:

## Functional Combinator
A higher-order function, usually curried, which returns a new function changed in some way. Functional combinators are often used in [point-free programming](#todo) to write especially terse programs.
