### ISSUE TITLE
Translate this repository to spanish.

### ISSUE THREAD

**Issue by idcmardelplata** [hemanth/functional-programming-jargon#133]
Hello, I think the project is great and I have taken the trouble to translate it completely into Spanish, I hope you can put the link in the list of translations, greetings and thanks for such a good initiative :)

https://github.com/idcmardelplata/functional-programming-jargon/tree/master

**Comment by jethrolarson** [comment]
Awesome!

**Comment by idcmardelplata** [comment]
Thank you @jethrolarson , I'm glad you like it, i'm should you make a pr to request that you integrate it into the translations?

**Comment by hemanth** [comment]
Yup!

**Comment by idcmardelplata** [comment]
@hemanth Ok, thanks, I'll do it
