### ISSUE TITLE
Monoid is a bad example when explaining a category

### ISSUE THREAD

**Issue by dmitriz** [hemanth/functional-programming-jargon#137]
Monoid is given as example of Category?

https://github.com/hemanth/functional-programming-jargon#categories

Monoid comes with **binary** operation, whereas functions (morphisms)
in a Catgory are unary, not binary. So it is very confusing to use Monoid as explanation.

A Category is really a collection of objects (types) and functions (aka morphisms) between types, sending values to values. Further, functions `a->b` and `b->c` can be composed, the composition is associative, and there is identity function `a->a` for each object `a`.

**Comment by jethrolarson** [comment]
Yeah, current definition is very wrong. If you can come up with a
explain-like-I'm-five definition I'd welcome it.
