### ISSUE TITLE
Hindley-Milner type signatures

### ISSUE THREAD

**Issue by jasonbellamy** [hemanth/functional-programming-jargon#14]
Should there be a small section describing Hindley-Milner type signatures? I am just recently getting into the world of functional programming and know that at first I was confused about all these "strange comments" in the code.

**Comment by hemanth** [comment]
Yes there must be, I am guessing you are reading Dr.Boolean's book ;) ?

**Comment by jasonbellamy** [comment]
Yeah, I just finished it a couple weeks ago. It was an interesting read, and definitely piqued my interest in functional programming.

**Comment by hemanth** [comment]
:+1:

**Comment by jethrolarson** [comment]
Problem is that there's not really a standard for the signatures in JS. The examples I've seen have been an adaptation from Haskell or F# or just off-the-cuff.

**Comment by CrossEye** [comment]
It's far, far too large for here, and still not finished, but I just created [a document][hm] explaining how Ramda uses these.

  [hm]: https://github.com/ramda/ramda/wiki/Type-Signatures

**Comment by hemanth** [comment]
@CrossEye wow!

**Comment by jethrolarson** [comment]
There's a small section in the document on type signatures now. Can we resolve?

https://github.com/hemanth/functional-programming-jargon#type-signatures

**Comment by jasonbellamy** [comment]
Thanks @jethrolarson
