### ISSUE TITLE
Volunteering - Russian Translation 

### ISSUE THREAD

**Issue by fasvald** [hemanth/functional-programming-jargon#142]
Hello.

I can help you with a Russian translation if you want.

--

P.S. Thanks a lot for this repo )

**Comment by hemanth** [comment]
Thanks, please feel free to do it, just don't forget to link back to this repo ;)

**Comment by Egorvoz** [comment]
@hemanth :+1:

**Comment by SeanSilke** [comment]
@Egorvoz I can help with translation if you needed. Please point to it, сan't find it in your fork.

**Comment by Egorvoz** [comment]
@SeanSilke i will send you a repo link in couple of days :)
Sorry for ignoring (has a lot of tasks at work). I hope you will understand me.

**Comment by maksugr** [comment]
is it has any progress here?

**Comment by Bannerets** [comment]
@maksugr https://habr.com/post/310172/

**Comment by maksugr** [comment]
@Bannerets good! but it would be great to have translation on github and link to it in this repo.

**Comment by epogrebnyak** [comment]
Another Russian translation, abridged, but with Haskell examples: https://github.com/epogrebnyak/functional-programming-jargon/

**Comment by jethrolarson** [comment]
Added a link to @epogrebnyak 's translation. Thanks!
