### ISSUE TITLE
UnderscoreJS does not have "curry" function

### ISSUE THREAD

**Issue by palerdot** [hemanth/functional-programming-jargon#145]
In the **[Auto Currying](https://github.com/hemanth/functional-programming-jargon#auto-currying)** section, it is mentioned that **[UnderscoreJS](http://underscorejs.org)** has a currying function. But, there is no such function in UnderscoreJS library.

**Comment by jethrolarson** [comment]
Good observation. That should be lodash

**Comment by jethrolarson** [comment]
Lodash should have been capitalized I think
