### ISSUE TITLE
Translation for Bahasa Indonesia

### ISSUE THREAD

**Issue by wisn** [hemanth/functional-programming-jargon#157]
Hi!
This repository helped me out to understand functional programming jargon in a simple way. Thanks a lot!
I've forked and translated all of the jargons to my native language, Bahasa Indonesia.

Here is the repository: [wisn/jargon-pemrograman-fungsional](https://github.com/wisn/jargon-pemrograman-fungsional)

Please adds it :smile:

**Comment by hemanth** [comment]
Nice, just send a PR for the same.
