### ISSUE TITLE
I am confused (or the 'Value' section is wrong)

### ISSUE THREAD

**Issue by DanielHeath** [hemanth/functional-programming-jargon#159]
'Value' is described as `Anything that can be assigned to a variable`.

In the FP jargon I've heard, a function can be assigned to a variable but is not a value.

Am I just confused/wrong?

**Comment by GoToLoop** [comment]
For computers everything is a value. A function's value is its contiguous allocated block's starting memory address.

**Comment by DanielHeath** [comment]
I'm across that end of the stack :) was questioning the FP-jargon aspect (where I've heard 'value type' used to refer to data primitives).

**Comment by jethrolarson** [comment]
Functions are values. That's what makes them first-class in js

**Comment by DanielHeath** [comment]
Thanks :)
