### ISSUE TITLE
Monad description too brief

### ISSUE THREAD

**Issue by jethrolarson** [hemanth/functional-programming-jargon#16]
It doesn't cover what bind is supposed to accomplish or it's rules. It also doesn't state why someone would want to use it nor problems it solves.

I know this would be better stated as a pull-request but I wanted to throw this out there.

**Comment by hemanth** [comment]
The idea is to keep it brief, but yes if it's missing a main point, worth changing it :+1:

**Comment by jethrolarson** [comment]
It's definitely not brief any longer but I think it's now suffering _The Curse of the Monad_ now. I've done a little work to describe what chain does but I suppose it's not illuminating why monads are useful.

Maybe it should be as simple as

> An object with `chain` and `of` methods.

Explaining why Monads are useful gets hand-wavy or obtuse pretty fast.

**Comment by hemanth** [comment]
@jethrolarson Fixed it, thanks.
