### ISSUE TITLE
Explanation of `lens`

### ISSUE THREAD

**Issue by peteranny** [hemanth/functional-programming-jargon#166]
http://ramdajs.com/docs/#lens

Here is the keyword `lens` with no further explanation.
Wonder if its definition can be added here?

**Comment by hemanth** [comment]
We could pick up few things from this [paper](https://maartenfokkinga.github.io/utwente/mmf91m.pdf).

**Comment by jethrolarson** [comment]
Yeah. That sounds like a good idea. Lenses are cool.
