### ISSUE TITLE
TOC refers to absent anchor tags

### ISSUE THREAD

**Issue by MaggieLeber** [hemanth/functional-programming-jargon#169]
The TOC at the top of the site assumes anchor tags on each entry, but they are not present.

For example: 

`https://functional.works-hub.com/blog/Functional-Programming-Jargon#partial-application`

**Comment by jethrolarson** [comment]
That site is not maintained by us. They're running some kind of fork of the readme and improperly compiling the markdown. The link for partial application on github seems to work fine so I don't think there's anything to fix on our end
