### ISSUE TITLE
Idempotent inaccurate

### ISSUE THREAD

**Issue by niclash** [hemanth/functional-programming-jargon#184]
Although the provided explanation that "f(x) is idempotent, if and only if f(x) == f(f(x))" is the original academic meaning, in industry jargon it not the case. There, an idempotent call (function, procedure, rpc,...) is one that can be repeated with the same inputs many times, returning the same value and not causing any additional side effects (say, issue the payment request many times).

I suggest that some wording of this is added.

**Comment by jethrolarson** [comment]
The aim of this glossary is not to be a dictionary of all possible uses of
each word but but to focus on functional programming meanings. Adding
definitions for other usage outside of that could confuse readers. In
particular, idempotent procedures focus on external effects which are
counter to functional programming goals so if we add anything about that it
should be as contrast

**Comment by niclash** [comment]
Ok. Np.
