### ISSUE TITLE
Volunteering - Polish translation

### ISSUE THREAD

**Issue by Deloryn** [hemanth/functional-programming-jargon#185]
Hi, I've just started translating your text into the Polish language. Do I have your agreement to continue?

**Comment by jethrolarson** [comment]
Translations are welcome, just link to this repo in there somewhere and then we can add a link to your repo.

**Comment by Deloryn** [comment]
Okay, I've added the link "Link do oryginału (wersja angielska)", which redirects to the original repo

**Comment by Deloryn** [comment]
I've finished the translation and added link to this repo. Only corrections left. Here is URL to my repo:[https://github.com/Deloryn/functional-programming-jargon](https://github.com/Deloryn/functional-programming-jargon)

**Comment by jethrolarson** [comment]
Sorry, I haven't been paying attention to this project but I just added the link to your translation to the main doc. Thanks!
