### ISSUE TITLE
A question about the use `chain` and `of` in the Monad entry

### ISSUE THREAD

**Issue by ethagnawl** [hemanth/functional-programming-jargon#23]
Is there any reason `chain` and `of` were used instead of the more common (Wikipedia, Haskell, etc.) `bind` and `return` in the Monad entry? Are these names commonly used in some other literature, language or library?

My concern is that people who read/grok the (great!) example contained herein and want to explore further will be thrown when they see `bind` and `return` used in most other definitions, tutorials, etc.

**Comment by jethrolarson** [comment]
Yeah, those names are from the fantasyland specification

**Comment by jethrolarson** [comment]
https://github.com/fantasyland/fantasy-land

**Comment by jethrolarson** [comment]
It would be okay to add aliases though

**Comment by ethagnawl** [comment]
> Yeah, those names are from the fantasyland specification

Oh, cool - I wasn't aware of this project.

> It would be okay to add aliases though

Unless you have something specific in mind, I could put a PR together.

**Comment by jethrolarson** [comment]
Feel free. I would be mindful that bind and return are already things in
js. I'd considered doing this but I didn't know if I should also include
scala, F#, or others

**Comment by ethagnawl** [comment]
Alright, [here's](https://github.com/hemanth/functional-programming-jargon/pull/24) a first pass at that PR.

**Comment by ethagnawl** [comment]
Closed via #24.
