### ISSUE TITLE
Functor example does not make any sense

### ISSUE THREAD

**Issue by alper** [hemanth/functional-programming-jargon#238]
In Functor there's:

```javascript
const f = x => x + 1
const g = x => x * 2

some(1).map(x => g(f(x))) // = some(3)
some(1).map(f).map(g) // = some(3)
```

Especially the second but maybe both should by any reasonable intuition be `4`?

Take `some(1)`, map it through `f`, result `2`, map it through `g`, result `4`.

If for some reason this is different than reading order, then I would say that that reason is wrong.

Also I can't try this out because there's no REPL anywhere?

**Comment by CrossEye** [comment]
@alper: You're right.  The example [is wrong][rr].  Care to create a PR to fix it?


  [rr]: https://ramdajs.com/repl/#?console%20.clear%20%28%29%0Aconst%20some%20%3D%20Maybe.Just%0A%0Aconst%20f%20%3D%20x%20%3D%3E%20x%20%2B%201%0Aconst%20g%20%3D%20x%20%3D%3E%20x%20%2A%202%0A%0Aconsole%20.log%20%28some%281%29.map%28x%20%3D%3E%20g%28f%28x%29%29%29%29%20%2F%2F%20%3D%20some%283%29%0Aconsole%20.log%20%28some%281%29.map%28f%29.map%28g%29%29%20%2F%2F%20%3D%20some%283%29

**Comment by marcwrobel** [comment]
Done in #240.
