### ISSUE TITLE
Inconsistencies in types definitions

### ISSUE THREAD

**Issue by boris-marinov** [hemanth/functional-programming-jargon#29]
The following two definitions are both correct, but they are inconsistent: 

> A monoid is some data type and a two parameter function ...
> 
> An object with a map function that adhere to certains rules. ...

I don't know which of the two is better. The "object with some methods" style of definition, limits us in some ways, for example we cannot say "pure functions form a monoid under functional composition".  The other one seems impractical. Maybe we should incorporate both.

**Comment by jethrolarson** [comment]
Functions are objects so it's not too much worry to me

**Comment by boris-marinov** [comment]
Not my point. 
I think we should either say A monoid is... 
- An object with a map method which accepts a function.
- A datastructure plus some method which accepts that datastructure plus a function.

We all know that these two things are essentially the same but we should stick with one of them in order to be consistent (else a person who is reading the docs would presume that there is some difference between the two concepts.

Another way that is more verbose but also clearer is to say both things. Something like...

"A monoid is an object with a map method (or a separate function)..."

Cheers everyone.

**Comment by jethrolarson** [comment]
I think we should say function instead of method. While methods can be
used, that won't always be true and anything you can do with methods you
can do with functions. Number and add are a monoid but i can't don't expect
it to be implemented as a method, nor for compose

**Comment by jethrolarson** [comment]
All references to "method" have been removed from the document so I think we can call this resolved.
