### ISSUE TITLE
Functor identity not ===

### ISSUE THREAD

**Issue by marcusnielsen** [hemanth/functional-programming-jargon#46]
``` js
const before = [1,2,3]
const after = before.map(x => x)
before === after // Returns false
for(let i = 0; i < before.length; i++) {
  before[i] === after[i] // Returns true
}
before.length === after.length // Returns true
```

First equals-check is for the reference, and `after` is a shallow copy of `before`. Easiest way to explain might be to write `Assert.deepEqual(before, after)` and define Assert.deepEqual somewhere so the code still looks minimal.

**Comment by jethrolarson** [comment]
We could alternatively use ≍ or we could define setoid and use that `equals` as the way to evaluate equivalence.
