### ISSUE TITLE
Could I add Declarative ?

### ISSUE THREAD

**Issue by linguistbreaker** [hemanth/functional-programming-jargon#61]
https://en.wikipedia.org/wiki/Declarative_programming

Functional programming, and in particular purely functional programming, attempts to minimize or eliminate side effects, and is therefore considered declarative.

Basically differentiate it from imperative programming and give an example - SQL.

**Comment by jethrolarson** [comment]
It could possibly be useful. However you can be functional without being declarative (explicit control flow using monads) and you can be declarative without being functional (SQL and other DSLs).

**Comment by linguistbreaker** [comment]
Hmm good point.
