### ISSUE TITLE
Etymology is missing

### ISSUE THREAD

**Issue by adamryczkowski** [hemanth/functional-programming-jargon#67]
I find that it would be much easier to understand and remember unknown terms, if etymology (origin) of their name is given. At the moment not a single entry has it.

Do you have any plan/wish to include it?

**Comment by jethrolarson** [comment]
I don't think so. We're trying to keep these descriptions brief. Going into
a lot of detail would compete with that goal

**Comment by hemanth** [comment]
> keep these descriptions brief

is the goal!

**Comment by adamryczkowski** [comment]
Well, I think it is a pity, because human brain prefers learning from stories in contrast to pure mathematical facts. afaik there is no place for such information on the Net. 

Anyway, thank you very much for your effort! Even without that information your project is very valuable and I'm very glad you share it.

**Comment by MattMcFarland** [comment]
@adamryczkowski I find your proposal interesting, maybe we can make a repo?

**Comment by jethrolarson** [comment]
Maybe Wikipedia would be the right place?

**Comment by adamryczkowski** [comment]
@jethrolarson Yes, it may be. Good point. (On the second thought, it applies to the functional-programming-jargon repository as well).

**Comment by hemanth** [comment]
@MattMcFarland @adamryczkowski Why not we create a wiki here and link them?
