### ISSUE TITLE
"Applicative Functor" has zero detail

### ISSUE THREAD

**Issue by tabatkins** [hemanth/functional-programming-jargon#72]
The "Applicative Functor" section has basically zero detail, giving no insight as to what the concept is useful for.  Suggested rewrite:
---

Ordinary functors "stand alone" - you can `map` functions over them, but if you've got two functors, you can't do anything with them as a pair.  An "applicative" functor knows how to combine with other functors of its type, allowing you to work with multiple functor values at the same time.

In addition to the standard `map`, an applicative functor has an `ap` function, which combines together
1. A _function_ wrapped in the functor, and
2. An _argument_ wrapped in the functor

For example, if you have an array of functions:

```
let funcs = [a => a+1, b => b*5];
```

and an array of values you want to map those functions over:

```
let vals = [1, 10, 100];
```

The standard applicative implementation of `Array` will do that for you, applying each function to all of the values, using `ap`:

```
funcs.ap(vals) == [2, 11, 101, 5, 50, 500];
```

(There are other ways to make `Array` applicative; for example, a "ziplist" implementation would instead combine the first function with the first argument, the second function with the second argument, etc, yielding `[2, 50]` from the code above.)

More usefully, applicative functors let the mapping function take multiple arguments:

```
let plus = (x,y) => x+y;
let arg1 = [1, 2, 3];
let arg2 = [10, 100];
[plus].ap(arg1).ap(arg2) == [11, 101, 12, 102, 13, 103]
```

(Note that for this to work, you still need to put the function into the functor. Also, the function has to be capable of being partially-applied, so the first `ap` can give it the first argument, resulting in an array of partially-applied functions, then the second `ap` can finish them off by giving the second argument.)

**Comment by jethrolarson** [comment]
Yeah, the definition is pretty brief like most of the descriptions on this document. I don't really want us to go into too much detail in this document but I think the definition can give a little more "why". I'll see if I can spruce it up a bit with some of your suggestions.

**Comment by tabatkins** [comment]
Yeah, feel free to cut my stuff down a ton. It's just that the current definition gives you absolutely no idea wtf it's actually useful for.  "Uh, so you can put the function into an array, and then it's exactly the same as .map, and...?" ^_^  The core insight is that it lets you combine together "sibling" functors (just like monadics lets you combine together nested functors).

**Comment by jethrolarson** [comment]
Applicative could still be better but I think we can call this addressed for now. 

It might be illuminating if we had some examples to `Maybe` using `.ap` for composing validation.

**Comment by tabatkins** [comment]
Easy Maybe example is grabbing two or more values from a dict (which returns a Maybe, to represent the key not being in there), then calling a function on the values; ap() gives you the obvious Maybe result "for free", failing if either of the inputs failed.
