### ISSUE TITLE
Would be great to see a 'Why?' section for each entry

### ISSUE THREAD

**Issue by dflock** [hemanth/functional-programming-jargon#76]
Ok, so you've explained... currying or functors. Great. But _why_ would I want to curry a function? What's the benefit of doing that? How is it used in the real world?

**Comment by jethrolarson** [comment]
That's a great question but one that's better served by a blog article than a glossary. I remember this being a decent explanation http://fr.umio.us/favoring-curry

**Comment by hemanth** [comment]
Maybe this is a good candidate for the wiki?

**Comment by dflock** [comment]
Thanks for that link @jethrolarson - nice explanation.

Maybe each entry could have a 'Read More' section, with links to further reading, Wikipedia articles, blogs, the Wiki here, etc...?

**Comment by Alhadis** [comment]
> But a curried version behaves more usefully:
```js
formatName1("John", "Paul");
//=> "John Paul undefined");
formatName1("John", "Paul")("Jones");
//=> "John Paul Jones"
```

Ｅ Ｐ Ｉ Ｐ Ｈ Ａ Ｎ Ｙ
<img src="https://cloud.githubusercontent.com/assets/2346707/17647363/f8ea57a4-6230-11e6-99cb-919bd33d2d6f.png" width="300" title="Grokked AF" />

**Comment by jethrolarson** [comment]
Your response inspired me to add a link to the article to the curry section

**Comment by Alhadis** [comment]
![12687866_924665384298430_4879727175629932168_n](https://cloud.githubusercontent.com/assets/2346707/17779022/8a57c674-65a9-11e6-887c-d3507a73ddf3.jpg)

**Comment by Alhadis** [comment]
BTW, [here's](https://github.com/Alhadis/Snippets/commit/ce4ad89e5fc922b0a00e795e688264caa0ce7e96) a practical use for currying in JavaScript I wrote. =)

```js
/**
 * Curried method to append multiple nodes at once.
 *
 * @example addTo(node)(el1, el2, …)
 * @example node = addTo(node)(…)[0]
 * @return {Function}
 */
function addTo(parent){
	let count = 0;
	let target = parent;
	
	const fn = (...nodes) => {
		let lastElement;
		
		for(let node of nodes){
			if("string" === typeof node)
				node = document.createTextNode(node);
			else
				lastElement =
				fn[++count] = node;
			target.appendChild(node);
		}
		
		target = lastElement || target;
		return fn;
	};
	fn[count] = target;
	return fn;
}
```

So to produce the following HTML...

```html
<header id="top">
	<h1>
		<a class="permalink" href="#top">
			Heading
		</a>
	</h1>
</header>
```

... you'd use:

```js
addTo(document.body)
	(New("header", {id: "top"}))
	(New("h1"))
	(New("a", {className: "permalink", href: "#top"}))
	("Heading");
```

(This example uses my beloved [`New`](https://github.com/Alhadis/Snippets/blob/ce4ad89e5fc922b0a00e795e688264caa0ce7e96/js/utils.js#L1175-L1192) function to generate HTML elements easily).

Hope this helps somebody! Let me know if my curry-cooking sucks!

**Comment by jethrolarson** [comment]
I think we should address the "Why" via links either to the wiki or to external resources. We've done that for curry and a couple others. Ensuring that every term has a approachable "why" would be quite the undertaking so I think we should address those in individual issues/PRs.

We could track this as an initiative and tag the issues/PRs with a "Why" tag. Either way I think this issue is a little too open ended to be left open indefinitely. If there are specific terms that you really want to see a motivation for feel free to open a issue specific to that term.

**Comment by Alhadis** [comment]
Hey @jethrolarson, I'm [still waiting for you to answer](https://github.com/hemanth/functional-programming-jargon/issues/111#issuecomment-257804299). =)
