### ISSUE TITLE
Pointed Functor Example

### ISSUE THREAD

**Issue by gsklee** [hemanth/functional-programming-jargon#77]
``` javascript
Array.prototype.of = (v) => [v];

[].of(1) // [1]
```

However, there is only [Array.of](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/of), not `Array.prototype.of`. Is this an error, or is an `Array.prototype.of` implementation details missing here?

**Comment by jethrolarson** [comment]
Yeah. It's an error

**Comment by gsklee** [comment]
Okay, sorry, my bad - the implementation details of `Array.prototype.of` is clearly provided. Not sure what I was saying.

Since an Array instance is a functor due to the presence of `Array.prototype.map`, an Array instance can not possibly be a pointed functor if the `of` method is not implemented by the users as `Array.prototype.of`, correct? If that's the case, then I'd suggest making it clear on the docs that this is not an error and should not be confused with `Array.of`.

**Comment by jethrolarson** [comment]
Debatable. I think these laws hold as long as a function exists which
satisfies the rules regardless of whether it's a method or not

**Comment by jethrolarson** [comment]
fantasyland is bit more strict about the implementation than the definition
needs to be

**Comment by jethrolarson** [comment]
Close?
