### ISSUE TITLE
Array.prototype.map() in javascript doesn't preserves integrity

### ISSUE THREAD

**Issue by jonasporto** [hemanth/functional-programming-jargon#93]
I think that Array map method surprisingly doesn't apply as example of Functor

`var a = [1, 2 , 3];`
`a.map(x => x) === a // false`

the same for
`const b = [1, 2, 3];`
`b.map(x => x) === b // false`

**Comment by jethrolarson** [comment]
Yeah we shouldn't use reference equality to define functor. We could use
the setoid `.equals` for structural equality

**Comment by isiahmeadows** [comment]
I'll note that Fantasy Land defines equivalence as [structural equality, not referential equality](https://github.com/fantasyland/fantasy-land#terminology). That's probably most relevant here.
