### ISSUE TITLE
Software updates 

### ISSUE THREAD

**Issue by Timmy461978** [hemanth/functional-programming-jargon#94]
Samsung galaxy core prime

**Comment by jethrolarson** [comment]
Wut

**Comment by jethrolarson** [comment]
Close

**Comment by hemanth** [comment]
![3oEjHJBolSjqwiZ2rS](https://camo.githubusercontent.com/5783a88fd0ef9ef0d80018f0f8ed3bf223af1a3a/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f336f456a484a426f6c536a7177695a3272532f67697068792e676966>)
